- APISpec.md
> API仕様をWikiからレポジトリ内のファイルに移行

- app/front/components/ChatRoom.vue
- app/front/components/TextArea.vue
新しいメッセージを送信した場合、いちばん下までスクロールする
> scroll by new message

- app/front/components/ChatRoom.vue
- app/front/components/TextArea.vue
スクロールが下までされているかの関数isScrollBottomの定義とサンプル書いた
受信の実装終わり次第関数入れる感じで
新しいコメントボタンも同様に押したらスクロールできるようになった
> スクロール判定、新しいコメントボタン

- server/package-lock.json
- server/package.json
- server/tsconfig.json
> fix build of server

- .vscode/settings.json
- app/front/components/ChatRoom.vue
- app/front/nuxt.config.js
- app/front/package.json
- app/front/pages/index.vue
- app/front/yarn.lock
- server/package.json
- server/src/app.ts
- server/src/ioServer.ts
- CORS対応とWebSocketが404になるエラーを解消
- **フロントのデータの持ち方を変更**。具体的には、コメント一覧の状態保持をChatRoomからIndexに移した。（WebSocketの通信の関係上）
- 部屋の入退室のWebSocket通信の実装
> クライアントサーバー間のWebSocketの調整

- server/src/ioServer.ts
- server/src/stamp.ts
一気に送ると通信量がエグいので。
多分2秒ごとに空でも送ってます(フロント側で何秒で届いてるか調節するの難しいかなと思ったので)
コネクションが生きているときは、2秒ごとにsetIntervalの中にいることだけは確認しました
> 2秒ごとにスタンプをおくる

- app/front/components/ChatRoom.vue
- app/front/components/Message.vue
- app/front/components/TextArea.vue
- app/front/models/event.ts
- app/front/models/userInputActions.ts
- app/front/pages/index.vue
- app/front/utils/getUUID.ts
- メッセージ・いいね送信周りのパラメータのバグを修正
- メッセージ・いいねのデータのやり取りをリファクタ
- ロジックをできるだけIndex.vueに集めています。 
- アイコンが存在しない場合にエラーが出ないように修正&リファクタ
-  uuid取得ロジックを外部関数化
> メッセージ送受信のバグ修正とリファクタ

- app/front/assets/scss/index.scss
- app/front/components/ChatRoom.vue
- app/front/components/TopicHeader.vue
- TopicHeaderコンポーネントにそのトピックがアクティブかどうか判定するprops（isActiveTopic）を追加
- isActiveTopic=trueならトピックの背景色を黄色に
- 現在はisActiveTopicの値はChatRoom.vueで直書き(true)で渡してる
> アクティブトピックの背景色変更

- app/front/assets/scss/index.scss
- app/front/components/ChatRoom.vue
チャットが追加された時にアニメーションを適用
（一部アニメーションがつかなかったので、追加時だけちょこっとだけアニメーションついてます。）
> アニメーションを追加

- app/front/assets/scss/index.scss
- app/front/components/Message.vue
- 背景色をグレーに
- ホバー無効、いいね不可
- 運営からの質問は通常の質問と同じデザイン
> 運営からのコメントの見た目を変更

- app/front/assets/scss/index.scss
- app/front/components/Message.vue
> 運営コメントにはアイコン下に「運営」の文字を入れる

- server/src/ioServer.ts
- server/src/stamp.ts
> console fix

- app/front/pages/index.vue
> 初回アクセス時モーダルの高さが最大で表示されるのを直した

- app/front/assets/scss/index.scss
- app/front/components/FavoriteButton.vue
- app/front/components/FavoriteEffectItem.vue
- app/front/utils/color.ts
- app/front/utils/waitedLoop.ts
- スタンプのアニメーション終了位置をランダムに変更
- 連続してスタンプを押した場合に、色が順に変わっていくように変更
- スタンプをたくさん押してもHTMLのdivが再利用されるように変更（パフォーマンス改善のため）
> スタンプにランダム性を追加

- app/front/assets/scss/index.scss
- app/front/components/ChatRoom.vue
- app/front/components/TopicHeader.vue
- app/front/package.json
- app/front/pages/index.vue
- app/front/utils/textExports.ts
- app/front/yarn.lock
- アイコンライブラリを追加（`vue-feather-icon`）
- コメントのエクスポートを実装
> コメントのエクスポートを実装

- app/front/components/AnalysisGraph.vue
グラフ一旦おわり
- 軸を削除(カチッとしたグラフ感の削除)
- 運営のコメントはカウントしない
> グラフの正規化、運営を弾いた

- server/src/ioServer.ts
- server/src/models/room.ts
- server/src/stamp.ts
Roomの中に実装し直した
Topicのなんかやったときに、
activeなトピックがある　かつ　タイマーがない　ならタイマーセット
activeなトピックがない　かつ　タイマーがある　ならタイマークリア
> send stamp every 2sec

- server/src/models/room.ts
#153
トピックの開始、終了、再開、一時停止時にBotメッセージを送る処理を追加
> Botメッセージを実装

- server/src/__test__/chat.ts
- server/src/events.ts
- server/src/models/room.ts
https://discord.com/channels/825706990343815188/825765422502641664/840818972278652948
> importエラーを解消

- app/front/components/ChatRoom.vue
> トピックのindexを0始まりにする

- app/front/assets/scss/index.scss
- app/front/components/TextArea.vue
文字数超えたときどこにエラーメッセージ表示したらいいかわからん
今の上限は300字
> [feat]コメント投稿時に文字数制限

- app/front/assets/scss/index.scss
- app/front/components/Message.vue
- app/front/components/SettingPage.vue
- app/front/models/contents.ts
２行実装するの難しそうだったから２０文字で...出すようにした
> [feat]リアクションで、n文字を超える場合は超えた分を...で省略する

- app/front/components/SettingPage.vue
> [fix] URLのコピーのハードコーディングを修正

- server/package-lock.json
issue #xxx
- なんか誰かに怒られてたらしいのでwsパッケージのバージョンをあげた
> wsパッケージのバージョンをあげた

- .idea/dataSources.xml
- .idea/sqldialects.xml
- server/src/database/database.ts
- server/src/database/ini.sql
- server/src/ioServer.ts
- server/src/models/room.ts
- server/src/stamp.ts
issue #232 
- stampsテーブルを作成
- topics has many stampsの設計にした
- userId(socketId)も記録するようにした
> スタンプをDBに保存するようにした。

- app/front/components/TextArea.vue
> [fix]先頭と末尾の空白、改行を削除

- server/package-lock.json
- server/package.json
- server/src/__test__/chat.ts
- server/src/ioServer.ts
- server/src/utils/crypt.ts
issue #xxx
- Socket.io Admin UIからサーバーにアクセスするための設定。リアルタイムに接続しているソケットの数や状態を確認できる。
- https://admin.socket.io/#/ にアクセスし、立ち上がっているサーバーのURL(パスの末尾に/adminを付けて)、username、passwordを入力する
> Socket.io Admin UIというモニタリングツールを導入した

- app/front/components/ChatRoom.vue
- app/front/components/KeyInstruction.vue
- app/front/components/TextArea.vue
- app/front/pages/index.vue
- app/front/store/device.ts
- app/front/utils/store-accessor.ts
issue #217 
ChatItemのVuex移行のコード見ながらOS情報判定する変数（DeviceType）の Vuex移行をした
> OS情報のVuex移行

- app/front/assets/scss/index.scss
> [fix]記号列改行バグの修正

- app/front/assets/scss/index.scss
> 【スマホ】グラフを閉じるボタンの修正

- app/front/components/CreateRoomModal.vue
issue #252 
・テキストエリアから追加するとき
　一つでも文字数overしているトピックがあれば全ての入力を受け付けない＆エラーメッセージ
・追加されているトピック名を後から変える時
　文字数overしたらエラーメッセージ
・全てのトピックが文字数以内の時のみ始めるボタンを表示
UI
> [fix]ルーム登録モーダルでトピック名が100文字を超えたら「始める」ボタンを押せなくする

- app/front/pages/index.vue
issue #271 
URLパラメタにルームIDが指定された場合の挙動が抜けていたので追加
共同管理者での動作を確認
> 複数管理者のバグを修正

- server/src/database/ini.sql
> DBスキーマを変更してtopicsテーブルのtitleカラムの最大長を100まで大きくした

- .idea/jsLinters/eslint.xml
issue #xxx
- IDEのeslint用の設定を更新しただけです。レビューいらないとは思いますけど一応誰かapproveお願いします。
> update IDE setting for eslint

- README.md
- app/shared/package.json
- sharedパッケージにビルドコマンドを追加した（#218）
- READMEを修正
> sharedのビルドコマンドを追加

- app/front/assets/scss/app.scss
- app/front/assets/scss/sidebar.scss
- app/front/assets/scss/sidebar_drawer.scss
- app/front/assets/scss/variables.scss
- app/front/components/Sidebar.vue
- app/front/components/Sidebar/SidebarContent.vue
- app/front/components/Sidebar/SidebarDrawer.vue
- app/front/pages/index.vue
issue #290 
- サイドバーを実装
- SidebarContent：サイドバーの中身を実装したもの
- SidebarDrawer：SidebarContentをラップして、ドロワー化したもの。 
- sassの色定数を追加
- sassのz-index定数を追加
> [UI] サイドバーのデザインを追加

- .idea/dataSources.xml
close #xxx
IDEの設定変えただけなので誰かapproveください
> IDEの設定を更新した

- .idea/dataSources.xml
- README.md
- app/front/assets/scss/index.scss
- app/front/assets/scss/variables.scss
- app/front/components/ChatRoom.vue
- app/front/components/KeyInstruction.vue
- app/front/components/TextArea.vue
- app/front/store/chatItems.ts
> テキストエリアの新UI

- app/front/assets/scss/index.scss
> Kayo/front/chat UI

- README.md
- app/server/README.md
- サーバーサイドを実行するために必要な準備をREADMEに記載した。
- 主にDBや環境変数の設定
- 本物のDBを使うかモックを使うかを実行時に設定できるようにしたほうがいいと思ったが、未対応
- #339
> Updated READMEs

- app/front/assets/scss/home/home.scss
- app/front/assets/scss/home/variables.scss
- app/front/pages/home.vue
- app/front/pages/room/create.vue
close #293 
ボタンのスタイルをちょっと変えたり、そのほかのcssちょっと変えたりした。
トップ画面UI
> マイページトップ画面UI

- app/front/components/Home/Modal.vue
- app/front/pages/home.vue
close #xxx
マイページスマホ画面のモーダル幅を修正
> マイページスマホ画面のモーダル幅

- .idea/watcherTasks.xml
誰でもいいのでapproveください
close #xxx
- IDEの設定の更新
> updated iDE setting for terraform fmt

- terraform/rds.tf
AWS側の自動アップデートでpostgresのenginがアップデートされていたのに追従
close #xxx
- terraformのRDS(databaseのリソース)のバージョンを更新
> updated postgres engin version

- doc/reference/sushi-chat-api.yaml
> API Specデグレを修正

- app/front/components/AnalysisGraph.vue
- app/front/components/ChatRoom.vue
- app/front/components/FavoriteButton.vue
- app/front/components/Message.vue
- app/front/components/SettingPage.vue
- app/front/components/Sidebar/SidebarContent.vue
- app/front/components/Sidebar/SidebarDrawer.vue
- app/front/components/TextArea.vue
- app/front/components/TopicHeader.vue
- app/front/pages/index.vue
- app/front/utils/ChartLine.ts
close #xxx
- ランタイムエラーの解消
- ESlintエラーの解消
> ランタイムエラーとESLintエラーを解消

- app/server/src/app.ts
- app/server/src/domain/admin/IAdminRepository.ts
- app/server/src/domain/admin/admin.ts
- app/server/src/infra/repository/admin/AdminRepository.ts
- Adminオブジェクト(とサンプルのリポジトリ)の作成
- app.tsで引数のエラーが起こっていたので修正
> created admin object

- package.json
- scripts/build_app.sh
- scripts/install_dependencies.sh
sharedパッケージのビルドが必要になったのに合わせてデプロイ時のスクリプトを更新した
close #xxx
> updated deploy process

- app/server/src/domain/admin/IAdminRepository.ts
- app/server/src/domain/admin/admin.ts
- app/server/src/infra/repository/admin/AdminRepository.ts
close #xxx
- AdminオブジェクトのmanagedRoomIdsをnullableじゃなくした
> admin's managedRoomIds is not null

- app/front/components/TopicHeader.vue
- app/front/pages/index.vue
TopicHeaderの中にsidebardrawer入れた
> revert topicheader

- app/front/components/Home/CreationCompletedModal.vue
- app/front/nuxt.config.js
> [fix]OGPのURL

- app/front/assets/scss/index.scss
- app/front/components/ChatRoom.vue
- app/front/components/Message.vue
- app/front/components/TopicHeader.vue
UI周りをdevelopにマージする
~寿司選択モーダルをdevelop-uiにマージしてから~
> develop-uI -> develop

- app/front/components/AdminTool/AdminTool.vue
- app/front/pages/index.vue
- doc/reference/sushi-chat-api.yaml
ルームの終了やろうと思って変なブランチ名にしてしまった
- ユーザーの入室
- swagger typoの修正
- 管理者の認証
- Topicsを取ってくること(REST)
- speakerTopicIdの代入
> [socket] ユーザーの入室

- app/front/components/Sidebar/SidebarContent.vue
- app/front/pages/home.vue
> お問い合わせフォーム作った

- app/front/assets/scss/home/home.scss
- app/front/assets/scss/home/variables.scss
> [fix]ルーム登録画面のスマホレイアウト崩れ

- app/server/src/infra/repository/User/UserRepository.ts
- app/server/src/service/user/UserService.ts
- delete duplicate user create
- insert topoics_speakers only when user.speakAt is set
close #xxx
- UserService.enterRoomでuserの作成処理を2回行っていたので、一回しか行わないように修正した
- UserRepository.create()で、user.speakAtがセットされている時のみtopics_speakersテーブルにinsertするようにした
> ENTER_ROOM でのユーザー作成処理のバグ修正

- app/server/src/service/room/RestRoomService.ts
> build room の修正

- app/front/components/ChatRoom.vue
- app/front/pages/index.vue
- app/front/pages/room/create.vue
- app/server/src/service/room/RestRoomService.ts
mount時にTopicStateがundefinedになるので順番を修正
ルーム作成時の型を合わせた
> TopicState周りのエラー解消/ルーム作成

- app/front/pages/home.vue
> マイページにログイン中のアカウントを表示する

- app/server/src/infra/repository/room/RoomRepository.ts
- app/server/src/ioServer.ts
- app/server/src/rest.ts
- app/server/src/service/admin/AdminService.ts
- app/server/src/service/chatItem/ChatItemService.ts
- app/server/src/service/room/RealtimeRoomService.ts
- app/server/src/service/room/RestRoomService.ts
- app/server/src/service/stamp/StampService.ts
- app/server/src/service/user/UserService.ts
close #xxx
- inviteAdmin時にrooms_adminsテーブルに関連レコードを登録するようにした
- 非同期処理になっている部分にawaitをつけた(直接関係ない作業一緒にやってすみません)
> inviteAdmin時にrooms_adminsテーブルに関連レコードを登録するようにした

- app/front/components/AdminTool/AdminTool.vue
- app/front/components/FavoriteButton.vue
- app/front/pages/index.vue
- app/front/store/chatItems.ts
- app/front/store/stamps.ts
- app/front/utils/socketIO.ts
> socketにidToken渡した

- app/front/components/AdminTool/AdminTool.vue
> 管理者ツールURLコピー完了アニメーション

- app/front/components/AdminTool/AdminTool.vue
- app/front/components/AnalysisGraph.vue
- app/front/components/ChatRoom.vue
- app/front/components/FavoriteButton.vue
- app/front/components/Message.vue
- app/front/components/SelectIconModal.vue
- app/front/components/Sidebar/SidebarContent.vue
- app/front/components/TextArea.vue
- app/front/nuxt.config.js
- app/front/pages/home.vue
- app/front/pages/index.vue
- app/front/plugins/socket.ts
- app/front/store/chatItems.ts
- app/front/store/stamps.ts
- app/front/utils/socketIO.ts
- app/server/src/ioServer.ts
> [socket]スタンプの送信/配信

- app/front/components/AdminTool/AdminTool.vue
- app/front/components/AnalysisGraph.vue
- app/front/components/ChatRoom.vue
- app/front/components/FavoriteButton.vue
- app/front/components/Message.vue
- app/front/components/SelectIconModal.vue
- app/front/components/Sidebar/SidebarContent.vue
- app/front/components/TextArea.vue
- app/front/nuxt.config.js
- app/front/pages/home.vue
- app/front/pages/index.vue
- app/front/plugins/socket.ts
- app/front/store/chatItems.ts
- app/front/store/stamps.ts
- app/front/utils/socketIO.ts
- app/server/src/ioServer.ts
#453 マージ後に
アクティブユーザー数取得(取っただけ)
ルーム終了(管理者ツールでstate変わったのを確認)
> [socket] PUB_USER_COUNT, ADMIN_FINISH_ROOM

- app/front/assets/scss/sushiselect.scss
- app/front/components/NotFound.vue
- app/front/components/NotStarted.vue
- app/front/components/SelectIconModal.vue
close #xxx
背景が途中で切れてるのを修正
レスポンシブ対応
> 寿司選択画面のスタイル調整

- scripts/start_app.sh
> fix deploy start app command

- app/front/assets/scss/lp.scss
> LPのスタイル崩れを修正

- app/server/src/infra/repository/room/RoomRepository.ts
close #xxx
- systemメッセージを保存できる様に修正した
- roomの再構築時にsystemuserを取得していなかったのが原因
> retrieve system user on RoomRepository.find()

- scripts/start_app.sh
- scripts/stop_app.sh
- terraform/deploy.tf
close #xxx
- 誰でも良いのでapproveください...
> fix deploy configuration

- app/front/pages/index.vue
> roomIdクエリがない場合/loginにリダイレクト

- app/server/src/database/seed/topic_states.sql
> fiix seed topic states

- app/front/assets/scss/admin.scss
- app/front/components/TextArea.vue
> [fix]質問投稿時にcmd+enterが効かない

- app/server/src/domain/user/IconId.ts
> fix IconId validation to ues shari

- app/front/assets/scss/index.scss
- app/front/components/Message.vue
- app/front/components/TextArea.vue
> textareaの高さ合わせた

- app/server/package.json
- app/server/src/__test__/chat.ts
- app/server/src/utils/topics.ts
- yarn.lock
> E2EテストのREST部分を作成

- app/front/assets/scss/index.scss
- app/front/components/AdminTool/AdminTool.vue
- app/front/components/Message.vue
- app/front/pages/index.vue
- app/front/pages/invited.vue
- app/front/pages/room/create.vue
- app/front/store/topicStateItems.ts
close #531 
- リアクションを一度しか押せないように変更（フロントのみ対応）
- topicIdの型をnumberに統一
> スタンプを一度しか押せないように変更

- app/front/components/ChatRoom.vue
- app/front/components/TextArea.vue
> リプライ時にtextareaにフォーカスする

- .github/labeler-develop.yml
- .github/labeler-main.yml
close #537 
- .github/labeler-***.ymlにディレクトリごとの設定を追加した
- labeler-develop.ymlとlabeler-main.ymlで重複定義をしなければならない。labelerのactionを使っている以上仕方なさそうだが、更新の際に若干めんどそう。
https://github.com/actions/labeler
> 自動ラベリングの設定を増やした

- app/front/assets/scss/admin.scss
- app/front/assets/scss/home/home.scss
- app/front/assets/scss/home/variables.scss
- app/front/assets/scss/lp.scss
- app/front/assets/scss/sushiselect.scss
- app/front/assets/scss/variables.scss
close #608 
- タイムスタンプの幅を最大値でも改行が入らないよう直した
- vscodeでエラーを吐いていた変数の書き方を揃えた
- homeの下部にあった謎の余白を消した
> timestampの幅修正

- app/front/assets/scss/index.scss
- app/front/components/ChatRoom.vue
- app/front/pages/room/create.vue
close #638 
- タブ切り替え時のスクロール処理を追加
> タブ変更時に下までスクロールするように変更

- app/front/assets/scss/index.scss
- app/front/components/Message.vue
- app/front/components/TopicHeader.vue
close #642 
- ピン留め、リプライの最大行数を2行に
- divダグだがカーソルが当たるようにした
> line-clampが効いていなかったのを修正

- app/front/components/ChatRoom.vue
- app/front/components/TopicHeader.vue
> チャット履歴ダウンロードの修正

- app/server/src/service/admin/AdminService.ts
> fix: fetch limited number of rooms to avoid lack of connection pool

- app/front/store/auth.ts
- app/front/utils/getIdToken.ts
close #670 
- firebaseのインポート方法を推奨される形に修正
> Firebaseのインポート方法を改善

- app/front/components/ChatRoom.vue
- app/front/nuxt.config.js
close #643 
- 不要なエラーハンドリングを削除した。
> 不要なエラーハンドリングを削除

- app/front/utils/socketIO.ts
close #669
変に貼り直していたソケットを引き継げるようにした。
リロードせずにログインし直せる同線があったらどうなるんだろうと思ったけど、ログインし直すのにリロードは必要かなぁと思い、考えないことにしました。
> fix socket cash condition
