osushi-academy/sushi-chat

server/src/ioServer.ts, server/src/stamp.ts
30秒ごとに空のイベント送ります。マジで空やけど、名前くらいつけてもいいのかもしれない。
ちなみに、
’io.on("connection", (socket) => {hogehoge})’
の中に書くとユーザーの数分実行されるらしく、修正しました
’io.once("connection"'
でもできるはずだけど効果なかった……
=> 30秒でイベント送信(後修正)

app/front/pages/index.vue, app/front/utils/reserveSelectIcon.ts
開発時にモーダルが出てうるさいので、アイコンIDをlocalStorageに保存するように変更
- localStorageにアイコンIDが保存されている場合はその値を利用し、存在しない場合はモーダルを出す
=> アイコンをlocalStroageに保存する処理を追加

app/front/pages/index.vue
#167 
- ルームをオープンするボタンを管理者にのみ表示
- ハンバーガーボタンとドロワーを管理者にのみ表示
- ルームIDの表示を見やすくした
=> ルームをオープンするボタンが一般ユーザーにも表示されてしまうバグを解決

app/front/assets/scss/index.scss, app/front/components/TopicHeader.vue, app/front/pages/index.vue, server/src/models/room.ts
- コメントが投稿されたとき、投稿者を含む全ユーザーにメッセージを送信するように変更
- 今までは自分の投稿はローカルに反映させていたが、タイムスタンプが反映されない問題があったので、自分のコメントもサーバーから受ける形に変更
- ただ即時反映はしたいので、自分が投稿したコメントは即時反映させ、サーバーからタイムスタンプ付きのメッセージが届き次第、それに置き換える形で実装しています
- アクティブなトピックの雷ボタンを押せないように変更
=> 自分が投稿したコメントのタイムスタンプのバグを修正

app/front/assets/scss/index.scss, app/front/components/ChatRoom.vue, app/front/components/KeyInstruction.vue, app/front/components/Message.vue, app/front/components/TextArea.vue, app/front/models/contents.ts, app/front/pages/index.vue
mac: ⌘+enterで送信
windows: ctrl+enterで送信
smartphone(iphone/ipad/android): 表示しない
それ以外:windowsと同じ
=> デバイスによってctrl+enterで送信の表示を変える

app/front/components/SettingPage.vue, server/src/models/room.ts
issue #178 
- 停止ボタンが押された時にバックエンドへイベントを送る関数を呼び忘れていたので追加した。
=> 停止ボタンが動作しないバグを修正

app/front/assets/scss/common.scss, app/front/assets/scss/heart.scss, app/front/assets/scss/index.scss, app/front/components/Message.vue, app/front/components/UrlToLink.vue, app/front/layouts/default.vue, app/front/nuxt.config.js, app/front/pages/index.vue
issue #219 
issue #220 
- アイコンやinstructionなどがコピペ範囲に入るのを外した
- ~~user-scalable=noにしてみた(試験的)~~
- touch-action: manipulationにした(効いてなさそう)
- 選択中の文字が存在する場合、クリックしてもリアクションしない
- 全メッセージタイプでURLをハイパーリンクに変換
- URLをクリックした場合リアクションは発火しない
- 改行がうまく表示
=> [fix] 選択できるテキストの変更、URLに対応

app/front/assets/scss/index.scss, app/front/components/AnalysisGraph.vue, app/front/components/ChatRoom.vue
- 盛り上がりグラフをボタンで開閉可能にした
- 盛り上がりグラフの吹き出しから運営アイコンを削除した（違和感があったので）
=> 盛り上がりグラフを開閉可能にした

app/front/components/SettingPage.vue, server/src/models/room.ts
issue #179 
- トピック終了時の処理を関数に切り出し
- 質問をまとめて表示する機能を追加
- ついでに回答済みの質問には`[回答済み]`のラベルを追加
=> Botの質問一覧のメッセージが表示されないバグを修正

app/front/assets/scss/index.scss, app/front/components/TextArea.vue
300字以内なら非表示
文字数オーバーでオーバーした文字数が赤色(ツイッター風にマイナス表示)
issue #242
=> [fix] 文字数制限の表示を変更

app/front/components/AnalysisGraph.vue
=> [fix]ホバー時にコメント数が見えないように

app/front/components/UrlToLink.vue
issue #240 
英単語及びurlが長い場合の改行をするように修正
word-break: break-all
=> [fix] set word-break

app/front/assets/scss/index.scss
issue #xxx
スクロール可能要素が入れ子上に2つ存在していたため、片方をスクロール不可にした。
=> スクロール可能要素がダブってるのを修正

app/front/components/ChatRoom.vue, app/front/components/SelectIconModal.vue, app/front/components/SettingPage.vue, app/front/components/TextArea.vue, app/front/components/TopicHeader.vue, app/front/pages/index.vue, app/front/store/userItems.ts, app/front/utils/store-accessor.ts
issue #206 
管理者かどうかを判定するisAdminと自分のアイコンIdの情報をVuexに移行した
isAdminとmyIconIdを合わせてUserItem型とし、それをVuexに移行させた
=> ユーザー情報のVuex移行

app/front/assets/scss/index.scss, app/front/components/Message.vue, app/front/components/UrlToLink.vue
issue #255 
コメントの本文について
`word-break: break-all`を設定しているものの本文の領域が文字の長さに依存する状態だったので、
```css
.text{
flex: 1;
word-break: break-all;
}
```
とすることで文字数関係なく幅いっぱいまで領域が確保されるようにした
その結果、admin、質問、回答では改行バグが消えた。
adminではない一般ユーザーの（質問/回答ではない）コメントがうまく領域が確保されない
Message.vueの
```vue:Message.vue
<div v-if="message.target == null">
<UrlToLink :text="message.content" />
</div>
<div v-else>
<span :style="{ color: 'gray', fontSize: '80%' }" @click.stop>
<UrlToLink :text="`> ` + message.target.content" />
</span>
<UrlToLink :text="message.content" />
</div>
```
v-if、v-elseの部分を消すとうまくいくけど、なんでうまくいくのかやその直し方がよくわかっていない
=> [fix]Safariの改行バグ

app/front/components/AnalysisGraph.vue, app/front/components/ChatRoom.vue, app/front/components/SettingPage.vue, app/front/pages/index.vue, app/front/store/topicStateItems.ts, app/front/store/topics.ts, app/front/utils/store-accessor.ts
close #207
- topic
- topicState
のvuex
- 管理画面の便利ボタン削除
- 冗長な部分の削除
連想配列作成と代入のみ
socket周りもまとめた方がいい気がしたが、room周りをvuex化するとスッキリするのだろうか
=> Topic, TopicStateのvuex

doc/reference/sushi-chat-api.yaml
close #xxx
description / urlを廃止して、ピン留めに変更したため、関連するAPI定義を更新
- RoomStateに`archived`を追加
- `POST /room`からurl, descriptionを削除
- Roomモデルからurl, descriptionを削除
- `/ENTER_ROOM`からurl, descriptionを削除
- `/PUB_TOPIC_INFO` /`CHANGE_TOPIC_INFO` を削除
- `/POST_PINNED_MESSAGE`, `/PUB_PINNED_MESSAGE`を追加
- `/ENTER_ROOM`のレスポンスに`pinnedChatItemIds`を追加
=> ピン留めメッセージ追加に伴うAPI Spec修正

app/server/src/domain/room/Room.ts, app/server/src/infra/repository/room/RoomRepository.ts, app/server/src/rest.ts, app/server/src/service/room/RestRoomService.ts
close #xxx
get /room/:id/history の実装
合わせて RoomClass に ` _stamps` と `_pinnedChatItemIds` という配列を追加
`_stamps` はスタンプ投稿時に配列に追加する処理も書いている。
`_stamps`、`Stamp` 型自体が最新の定義と違うので、完璧なレスポンスにはなっていない。(これはDB周りの変更後に揃うと踏んでいる)
`_pinnedChatItemIds` は空配列が存在するだけ。SocketIO側の変更する時にピン留め処理が増えるはず。
=> ルームのヒストリー取得

app/server/src/domain/room/Room.ts, app/server/src/ioServer.ts, app/server/src/rest.ts, app/server/src/service/room/RealtimeRoomService.ts, app/server/src/service/room/RestRoomService.ts, app/server/src/service/room/commands.ts
close #xxx
PUT /room/:id/archive　実装
socketIO側の処理は削除
adminかどうかをassertするやつをRoomClassに追加、アーカイブ処理の前に確認するようにした
adminの情報をヘッダーからとってn(以下略
adminIdをちゃんと保存してないので、普通には確認できません。
RoomRepositoryのfindのreturnのうち、
`new Set<string>([]) /* これはadminIdsです。 */`
を
`new Set<string>([""])`
に、
`roomState`
を
`"finished"`
にすると、一応チェックできます。
=> Eri 0910/room archive

app/front/components/ChatRoom.vue, app/front/components/Message.vue, app/front/components/TopicHeader.vue
close #301 
- 対応するメッセージまでスクロール
- 一旦サイドバーを非表示
- topicIndexがないと怒られていたヘッダーの修正
=> 対応するメッセージまでスクロール/一旦サイドバーを非表示

app/front/components/Home/CreationCompletedModal.vue, app/front/pages/room/create.vue, app/server/src/rest.ts, app/shared/src/types/rest.ts
close #xxx
「この内容で作成」を押したときにルームを作成する、一応軽くバリデーション付き
型の修正
sessionに初期値入ってたの消した
idがなんか合わなかったので修正した
モーダルでbefore-openが呼び出されないので、値が渡せない。
/homeでルーム名入れてボタン押しても、次の画面に引き継がれていない
safariやっぱりボタン変
description入力欄がない
サーバーadminの登録ができていない(近藤さんタスク？)
=> ルーム作成 API繋ぎ込み

app/front/assets/scss/common.scss, app/front/assets/scss/sushiselect.scss, app/front/components/SelectIconModal.vue
close #xxx
- 寿司選択画面にルーム名と説明を追加
- レスポンシブ考慮済み 
- 寿司一覧のCSSを変更（アイコンのサイズが極小になるケースがあったので、サイズを固定にしました！）
- SP時に、横の線と●が表示されないように変更
=> 寿司選択画面に情報を追加

app/front/assets/scss/app.scss, app/front/assets/scss/index.scss, app/front/assets/scss/sushiselect.scss, app/front/components/TopicHeader.vue
close #318 
- ヘッダー3点リーダ内のUI
- ダウンロードボタンの挙動確認
- アクティブユーザー表示
- 繋ぎこみ
=> ヘッダー3点リーダ内のUI

app/front/apiClient/index.ts, app/front/assets/scss/home/variables.scss, app/front/pages/home.vue, app/front/pages/login.vue, app/front/pages/profile.vue, app/front/plugins/apiClient.ts, app/front/store/auth.ts
close #xxx
- authストア（firestoreの認証が同期されるVuex store）の変更に追従して、apiClientにtokenをセットするように変更
- 既存実装より認証済みユーザーがAPIを叩いた場合は自動でAuthorizationヘッダにidTokenがセットされるはず
- ログイン後のリダイレクト先を/homeに変更
- /homeのログアウトを実装
- /homeにprivateRoutesのミドルウェア（未認証状態でアクセスするとログインページへリダイレクトされる）を適用
- /homeのデザインを微修正
=> API呼び出し時にトークンがセットされる実装

app/front/components/ChatRoom.vue, app/front/components/TopicHeader.vue
close #469 
全表示<->質問と回答のみを表示
adminとspeakerの投稿も表示
senderTypeが今のdevelopのChatItemの型にないから一旦放置
=> chatItem絞り込み

app/front/components/FavoriteButton.vue, app/front/store/stamps.ts
スタンプのStoreへの追加は配信によって行うこととした(1クリックでスタンプアニメーションを呼ばれる回数が1回減る)
スタンプの重複判定
=> スタンプが複数回呼ばれていたのを直した

app/front/components/ChatRoom.vue
close #497 
ヘッダーにはtopicIndexが渡され、テキストエリアにはtopicIdが渡されてたせいでズレが発生していたのでtopicIdに統一
=> [fix]ヘッダーとテキストエリアでindex違う

app/front/assets/scss/index.scss, app/front/components/ChatRoom.vue, app/front/components/Message.vue, app/front/components/SelectIconModal.vue, app/front/components/TextArea.vue, app/front/pages/index.vue, app/front/store/userItems.ts
close #459 
senderTypeに応じてmessageの出しわけ(socketにspeakerIdわたした)
TextAreaに表示した
通常ユーザーの場合messageの上の白が気になるかも
senderType=system
=> senderTypeの出しわけ

app/front/assets/scss/admin.scss, app/front/assets/scss/common.scss, app/front/assets/scss/home/home.scss, app/front/assets/scss/home/variables.scss, app/front/assets/scss/variables.scss, app/front/components/AdminTool/AdminTool.vue, app/front/components/ChatRoom.vue, app/front/nuxt.config.js, app/front/pages/home.vue, app/front/pages/index.vue, app/front/pages/room/create.vue, app/front/utils/formatDate.ts
close #xxx
- イベント作成ボタンのバグを修正 #510 
- htmlの言語コードをjaに変更 #325 
- 日時表記のフォーマットを変更
- イベントの作成ページでセッション登録のUX改善
-  行挿入時に自動でフォーカスされるように変更
- ENTERで自動で次の行を挿入
- escで現在の行を削除
- inputが空の状態でdeleteを押すと行を削除
- キーボードの上下キーで、フォーカスを移動
- 質問文の文言の修正
- イベント名入力欄にplaceholderを設定
- 全体的にplaceholderの色を薄くした
- セッションの入力中にフォーカスが外れるバグを修正
- 全体的にボタンをbuttonタグで実装
- デザインを調整
- アイコンをmaterial-iconsからfeather iconライブラリに移行
イベント作成ページを重点的にみて欲しいです
=> Fix/yuta ike/fix bugs

app/server/src/rest.ts
close #xxx
- クライアントエラーの時にエラーログを書き込まないようにした
- エラーログがうるさく、本当に重要な通知を見逃してしまう危険がある
- クライアントエラーは基本的にこちら側で対応することはできないもの。もしサーバー側の問題ならクライアントエラーでなくサーバーエラーにするべき。
- クライアントエラーとサーバーエラーの切り分け。
- 現在、管理者認証必須のエンドポイントでトークンが渡されていない時のみクライアントエラーにしているが、存在しない部屋にアクセスした時など、他にもクライアントエラーにするべき箇所が多々ある。
=> not write error on client error

app/front/pages/index.vue
#549 のあとで
- TopicStateの変更に対してフロント側でActiveなTopicを探していた実装から、フロントでは毎度受け取った状態の変更のみを行う
- #519 の現象はサーバーとも要確認
#549 のあとに変更を取り込んで、動作を検証する
=> トピック変更のsocket通知修正

app/front/pages/room/create.vue
close #xxx
フロント側で意図せず、フロントで利用しているidをサーバに送ってしまっていたのが原因だったので修正した
=> トピックIDのずれを修正

app/front/components/FavoriteButton.vue, app/front/pages/index.vue, app/front/store/chatItems.ts, app/front/store/stamps.ts, app/server/src/__test__/testStampService.ts, app/server/src/domain/stamp/IStampFactory.ts, app/server/src/infra/factory/StampFactory.ts, app/server/src/ioServer.ts, app/server/src/service/stamp/StampService.ts, app/server/src/service/stamp/commands.ts, app/shared/src/types/socketio.ts, doc/reference/sushi-chat-api.yaml
close #466 
スタンプのIDを、chatItemと同様にフロントで生成するように変更
- [doc] API Specを修正
- [shared] API型を修正
- [front] StampStoreを修正し、自分が送ったスタンプを省く処理を追加
- [server] stampのidをフロントから渡ってきたものを利用するように変更
~~**#556 のバグは未修正です**~~
永田が修正してくれた
=> スタンプの仕様と実装を変更

app/front/pages/room/create.vue
close #513 
ルーム作成画面にdescription入力欄が抜けていたので追加した。
文字数制限
=> fix: ルーム作成時にdescriptionを指定できるようにする

app/front/assets/scss/common.scss, app/front/assets/scss/index.scss, app/front/components/ChatRoom.vue, app/front/components/Message.vue, app/front/pages/index.vue, app/front/store/chatItems.ts
close #584 
- 送信中のUI表示
- 送信失敗時のエラー表示 & 再送信ボタンのUIを追加
- メッセージの再送信処理を実装
- リアクション・スタンプの送信中・エラー・再送信処理（失敗してもそこまで影響がないため放置）
- 送信失敗
- ローディング
=> 送信失敗時のUIと再送信処理を実装

app/front/pages/index.vue
close #462
roomオブジェクトが空（=ローディングが終わっていない）ときに、isRoomStartedがfalseになってしまう。
ので、そのチェックをした。
真っ白ダサいけど放置しちゃった、
別案1 fetch終わったらフラグを立てる
なんかスマートじゃなくてやめた。
別案2 asyncDataを使う
問題は、同じfetchをボタンを押してできるようにしたいこと。methodsはasyncDataでは使えないので、二重実装を避けるにはここだけ別ファイルに切り出すか(いやだ)、ボタンを押したら画面全体がリロードされるようにする必要がある(なんかイケてない)
=> ルームアクセス時に一旦未開始の時の画面が現れるのを回避

app/front/pages/room/create.vue
close #543 
ルーム作成画面で日本語変換中にBackspaceをクリックした場合にカラムが消えてしまうバグを修正
https://gotohayato.com/content/496/
=> fix: ルーム作成画面で日本語変換中にBackspaceをクリックした場合にカラムが消えてしまう

app/front/apiClient/index.ts, app/front/pages/home.vue, app/front/pages/index.vue, app/front/pages/invited.vue, app/server/src/expressRoute.ts, app/server/src/rest.ts, app/shared/src/types/rest.ts
close #560 
- APIクライアントでurl queryを指定できないケースがあったので、url queryを指定できるように変更
- API定義でgetメソッドにrequest bodyを指定できる仕様にしていたが、getメソッドでrequest bodyは使わない方が良いので削除。伴ってフロントのAPIクライアントも修正
=> APIクライアントを修正

app/front/assets/scss/index.scss
close #641 
ChatItemが1行のときにpadding-bottomが大きくなってしまっていたので直した。
=> fix: ChatItemが1行の時padding-bottomが大きくなる

app/server/src/app.ts, app/server/src/ioServer.ts, app/server/src/utils/http.ts
close #628 
- 既存の`www.sushi-chat.com`の他に、プレビュー用のvercelのドメインからのCORSを正規表現でチェックして許可するようにした。
=> プレビュー用のドメインからのCORSを許可 

app/front/assets/scss/sushiselect.scss
close #633 
- 背景白く
- `width: 100%` にし、`max-width: 400px` を設定
=> スピーカー選択欄の幅を入るようにした

app/front/assets/scss/home/home.scss, app/front/assets/scss/home/variables.scss, app/front/components/Home/Modal.vue, app/front/pages/room/create.vue
close #346 
- ボタンサイズのCSSが効いていないのを効かせた
- テキストボックスと高さを合わせる
- スマホ実機でも入れ替えボタンを画面内に入れる
=> ルーム作成画面のレスポンシブ

app/front/components/ChatRoom.vue, app/front/components/TopicHeader.vue
close #639 
スマホ版(実機)でみれていなかったボタン
- 3点リーダー
- ピン留め削除
を表示した
スマホ版でvue-feather-iconsを使用している箇所が全て表示されているか確認した(chrome)
=> スマホで表示されていなかったアイコンを表示

app/front/pages/index.vue
close #640 
- ルーム終了時にRESTAPIを叩く
- トークの履歴と、ピン留めアイテムのみ取得(コメントはできない)
=> 終了時にアーカイブを取得

app/front/components/AdminTool/AdminTool.vue, app/front/package.json, yarn.lock
close #518 
-------
#680 をバグらせてしまったのでやり直し......ｽﾐﾏｾﾝ....
以下 #680 よりコピペ
-------
AdminToolのツールチップを標準→ライブラリに変更
型定義なくてライブラリ入れられなかったから`@ts-ignore`で握りつぶしてる
https://github.com/KABBOUCHI/vue-tippy/ issues/175
https://github.com/KABBOUCHI/vue-tippy
=> refactor: AdminToolのツールチップをライブラリのものにした-2

app/server/src/__test__/chat.ts, app/server/src/domain/admin/IAdminRepository.ts, app/server/src/domain/chatItem/IChatItemRepository.ts, app/server/src/domain/room/IRoomRepository.ts, app/server/src/domain/stamp/IStampRepository.ts, app/server/src/domain/user/IUserRepository.ts, app/server/src/infra/repository/User/EphemeralUserRepository.ts, app/server/src/infra/repository/User/UserRepository.ts, app/server/src/infra/repository/admin/AdminRepository.ts, app/server/src/infra/repository/admin/EphemeralAdminRepository.ts, app/server/src/infra/repository/chatItem/ChatItemRepository.ts, app/server/src/infra/repository/chatItem/EphemeralChatItemRepository.ts, app/server/src/infra/repository/room/EphemeralRoomRepository.ts, app/server/src/infra/repository/room/RoomRepository.ts, app/server/src/infra/repository/stamp/EphemeralStampRepository.ts, app/server/src/infra/repository/stamp/StampRepository.ts, app/server/src/service/admin/AdminService.ts, app/server/src/utils/delay.ts
close #672 
- 管理しているルーム一覧を撮るときにN+1になっていたのを修正
- リポジトリの中でDBのコネクションをパスして、同一の処理の中でDBのコネクションを複数確保しないようにした。
- インターフェースに実装の詳細が染み出してるクソ実装だけど、スピード優先で妥協している
=> ルーム一覧取得のDBコネクション枯渇問題を暫定対応していたのを修正

app/front/nuxt.config.js, app/front/pages/index.vue, app/front/pages/room/_id.vue
close #xxx
- 終了後のルームで一瞬寿司選択画面が表示されていたのでされないようにした
- ログイン状態で/indexに遷移した際一瞬画面が表示されていたのをされないようにした(これで対応として合っているのだろうか)
=> ローディング遷移時に遷移前のページを表示しない

app/front/pages/invited.vue, app/front/pages/room/_id.vue, app/front/store/stamps.ts
close #xxx
- `/room/_id` で`_id`が指定されていない場合に、window.alertの後、`/home`へリダイレクトさせた
- `/invited?roomId=xxx&adminInviteKey=yyy`で、roomIdが指定されていない、roomIdが間違っている、adminInviteKeyが間違っているの3パターンについて日本語のエラーメッセージを表示
- コメント等の削除
=> エラーハンドリングを追加
